using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using ToDoWebAPI.Modules;


//autogenerated class via VS - bridge beetween domain and db
namespace ToDoWebAPI.Models
{
    public class ToDoContext : DbContext
    {
        public ToDoContext (DbContextOptions<ToDoContext> options)
            : base(options)
        {
        }

        public DbSet<ToDoWebAPI.Modules.ToDo> ToDo { get; set; }
    }
}
